### ISSUE TITLE
Connecting with authorization

### ISSUE THREAD

**Issue by arvindnrbt** [neo4j-contrib/django-neomodel#15]
I get `Invalid IP address 'fe80::1%lo0'`  when calling .save(). Also tried install_labels and I have the same error. Can anyone say how to connect with server if auth is enabled? How to get the bolt url? Now I'm using the default config for url.

**Comment by adriancarayol** [comment]
Can you put the neo4j log and django traces?

**Comment by arvindnrbt** [comment]
Hey, sorry for the late response. The problem was that I was using special characters for the password like `user:pa$*word` and that didn't go well with the bolt url to be considered a valid url.
