### ISSUE TITLE
Can I use it for production?

### ISSUE THREAD

**Issue by goutomroy** [neo4j-contrib/django-neomodel#18]
Can I use it for production?  Is this the best way to integrate neo4j with django?

**Comment by adriancarayol** [comment]
forgiveness for slow to respond, i think yes, your production environment is very large?

**Comment by goutomroy** [comment]
Sorry for late response.Yes my production environment is very large.Its a movies and tv show discovery app.

Thanks in advance.

**Comment by adriancarayol** [comment]
@robinedwards I think you can close this ticket.
