### ISSUE TITLE
updated_at

### ISSUE THREAD

**Issue by HashRocketSyntax** [neo4j-contrib/django-neomodel#24]
Hey there. I am attempting to implement an updated_at = DateTimeProperty for my DjangoNode

```
created_at = DateTimeProperty(default_now=True)
updated_at = DateTimeProperty(default_now=datetime.now)

```
^ this does not update when I edit my DjangoNode

And if I attempt, instance.updated = datetime.now followed by instance.save in my update view then it throws the following error:
```
Attempting to **deflate** property 'updated_at' on <MyInstance...
  File "/path.../site-packages/neomodel/properties.py", line 119, in _validator
    raise exc_class(self.name, self.owner, str(e), obj)
```

**Comment by robinedwards** [comment]
This just sets the default value, once there is a value it wont overwrite it. You need to use a pre_save hook.

**Comment by laynetrain** [comment]
Thank you @robinedwards, did not know pre_save was a thing!

```
@receiver(pre_save, sender=Employee)
def employee_edit_timestamp(sender, instance, *args, **kwargs):
  instance.updated_at = datetime.now
```
^ still getting DeflateError, but I will keep trying

**Comment by laynetrain** [comment]
```
def MyModel(DjangoNode):
  ...  

  def save(self, *args, **kwargs):
     self.updated_at = datetime.now
     super(MyModel, self).save(*args, **kwargs)
```

save error if i attempt to override save

**Comment by robinedwards** [comment]
```self.updated_at = datetime.now()```

else you are setting it to the `now` method definition
