### ISSUE TITLE
django admin interface

### ISSUE THREAD

**Issue by samdeleu** [neo4j-contrib/django-neomodel#4]
Hey,

I have been playing around now.
The python manage.py install_labels seems to work.
Can i see the structure in the admin interface?

Kind regards
Sam

**Comment by robinedwards** [comment]
Hi

There is currently no support for django admin at the moment but i would
definitely like to add support for it!

**Comment by auvipy** [comment]
I think django model._meta API will be needed for it

**Comment by mostafa** [comment]
I tried to inject _meta with meta-programming, but it didn't work!

**Comment by adriancarayol** [comment]
when I have a little time, I will try to implement admin with django-neomodel

**Comment by dmp593** [comment]
Is there any update on the status of this feature?

**Comment by flyly0755** [comment]
also want to know is there any update with this issue???

**Comment by whatSocks** [comment]
@flyly0755 @dmp593 @samdeleu @mostafa @adriancarayol a first version of this is on master
