### ISSUE TITLE
neomodel 4.0.1 incompatibility

### ISSUE THREAD

**Issue by AmandaCLNg** [neo4j-contrib/django-neomodel#42]
neomodel 4.0.1 has changed `MAX_POOL_SIZE` in config.py to `MAX_CONNECTION_POOL_SIZE` 
This now causes django_neomodel to fail in apps.py during startup

**Comment by whatSocks** [comment]
hey @AmandaCLNg, are you still having issues?

**Comment by whatSocks** [comment]
fix incoming in next release
