### ISSUE TITLE
Can't connect django_model to neo4j instance

### ISSUE THREAD

**Issue by hugolvc** [neo4j-contrib/django-neomodel#44]
I made these setting on `settings.py`, as directed on  [Getting Started](https://pypi.org/project/django_neomodel/):

```
NEOMODEL_NEO4J_BOLT_URL = os.environ.get('NEO4J_BOLT_URL', 'bolt://neo4j:attractora@localhost:7687')
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_neomodel',
    'utils'
]
```
But I only get this error:
```
neo4j.exceptions.ServiceUnavailable: [SSLCertVerificationError] Connection Failed. Please ensure that your database is listening on the correct host and port and that you have enabled encryption if required. Note that the default encryption setting has changed in Neo4j 4.0. See the docs for more information. Failed to establish encrypted connection. (code 1: Operation not permitted)
```
I know the database is running and accesible because I connected neo4j browser to it and made changes. I tried with database versions 4.1.3 and 3.5.25, and nothing.

Where else can I look for the reason of this exceptio? Thanks a lot for your help.

Where else can I look for the reason of this exception.

**Comment by jacob-hutchings** [comment]
Maybe try adding

    NEOMODEL_ENCRYPTED_CONNECTION = False

to your settings.py

**Comment by whatSocks** [comment]
@hugolvc there have been some updates to the codebase - if you are still experiencing the issue please create a new issue
