### ISSUE TITLE
Django-Neomodel AttributeError: module 'neomodel.config' has no attribute 'MAX_POOL_SIZE'

### ISSUE THREAD

**Issue by JSv4** [neo4j-contrib/django-neomodel#48]
I was just trying to get django-neomodel setup for the first time, following your instructions [here](https://github.com/neo4j-contrib/django-neomodel) and ran into this error: 

```
Traceback (most recent call last):
  File "manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/usr/local/lib/python3.8/site-packages/django_neomodel/apps.py", line 20, in ready
    self.read_settings()
  File "/usr/local/lib/python3.8/site-packages/django_neomodel/apps.py", line 17, in read_settings
    config.MAX_POOL_SIZE = getattr(settings, 'NEOMODEL_MAX_POOL_SIZE', config.MAX_POOL_SIZE)
AttributeError: module 'neomodel.config' has no attribute 'MAX_POOL_SIZE'

```

This error message is getting thrown by the apps.py file in neomodel-django:

     def read_settings(self):
            config.DATABASE_URL = getattr(settings, 'NEOMODEL_NEO4J_BOLT_URL', config.DATABASE_URL)
            config.FORCE_TIMEZONE = getattr(settings, 'NEOMODEL_FORCE_TIMEZONE', False)
            config.ENCRYPTED_CONNECTION = getattr(settings, 'NEOMODEL_ENCRYPTED_CONNECTION', False)
            config.MAX_CONNECTION_POOL_SIZE = getattr(settings, 'NEOMODEL_MAX_CONNECTION_POOL_SIZE', config.MAX_CONNECTION_POOL_SIZE)

It looks like if you set NEOMODEL_MAX_CONNECTION_POOL in the django settings file it *should* provide the correct value *except* that wasn't working for me. The default value provided in getattr (config.MAX_CONNECTION_POOL_SIZE) is a property of the neomodel config object / module and is apparently not set by default. 

I figured I'd see what happened if I manually set config.MAX_CONNECTION_POOL_SIZE. Good news, it worked! So, I just added this to my settings.py:

    from neomodel import config    
    config.MAX_POOL_SIZE = 50

I confess I've not used getattr much, so I played around with it to get a better understanding of how it works. Here's the function definition:

     getattr(object, name[, default])

If default is set to an attribute that doesn't exist of an object or module, then getattr immediately throws an AttributeError, even IF the object and name values are valid and would otherwise return a value. 

So it seems like this may be a bug in the django-neomodel code? It looks like the library is expecting MAX_CONNECTION_POOL_SIZE to be set in the neomodel config when Django starts, but this is not the case, at least as of 1/22/21 using neomodel 4.0.1 and django-neomodel 0.0.4. I just checked the [neomodel source](https://github.com/neo4j-contrib/neomodel/blob/004d506932fa7a735bd63c39be9d4c8d66658baa/neomodel/config.py), and the weird thing is, it should have MAX_CONNECTION_POOL_SIZE set by default. 

Perhaps I missed something and was supposed to instantiate the config value elsewhere?

**Comment by whatSocks** [comment]
fix incoming in next release
