### ISSUE TITLE
DRF 

### ISSUE THREAD

**Issue by MajidHeydari** [neo4j-contrib/django-neomodel#50]
There is no guide for DRF and neomodel and DRF example?

**Comment by MajidHeydari** [comment]
http://127.0.0.1:8000/admin/
I went to go to address  error 
settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.

**Comment by dan-poling** [comment]
Hi @MajidHeydari,
[This tutorial](https://neo4j-examples.github.io/paradise-papers-django/) goes rather in-depth using DRF & neomodel. 
Good luck!
