### ISSUE TITLE
Support with Graphene-Django-Plus

### ISSUE THREAD

**Issue by sumitsharansatsangi** [neo4j-contrib/django-neomodel#54]
I was trying to implement graphQL with django-neomodel but didn't find it's support in it. Also, I didn't find anything else for it. I request you to please provide a support of it with Graphene-Django-Plus. Why I am saying Graphene-Django-Plus,instead of Graphene or Graphene-Django because it has some goodness like Permission manager, query Optimization and inbuilt Authentication.

**Comment by whatSocks** [comment]
hey @sumitsharansatsangi - you're talking about this library? https://github.com/0soft/graphene-django-plus

**Comment by sumitsharansatsangi** [comment]
Yeah, I am talking about https://github.com/0soft/graphene-django-plus library.

**Comment by nossila** [comment]
@sumitsharansatsangi I'm actively working on making it compatible with django's admin which is the basically the same with graphene-django, so I guess you can expect it to work soon. But wont be possible to fully support `graphene-django-plus` as it implements a few models which can't use `neomodel`, I think you would be able to use some features but the data would be split into an SQL database and Neo4j.

**Comment by nossila** [comment]
The issue is that `neomodel` is the ORM and it is not meant to run on django (which has its own ORM), instead we should be looking for a "django neo4j database engine", that would be more compatible with the whole django ecosystem.
