### ISSUE TITLE
Improve Instructions for Registering Admin

### ISSUE THREAD

**Issue by MajidHeydari** [neo4j-contrib/django-neomodel#60]
Can i see the structure in the admin interface?
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
how have to Authentication in django-neomodel

**Comment by whatSocks** [comment]
are you using master or latest release?

**Comment by MajidHeydari** [comment]
I use from version django-neomodel 0.0.6 and I not found tutorial that How to use Django admin in this django-neomodel

**Comment by nossila** [comment]
@MajidHeydari you need to setup a database in `settings.DATABASES` and run the migrations because all django admin's authentication still goes through django models

**Comment by whatSocks** [comment]
The latest release (today, 0.0.7) has a beta version of the admin (nodes only). 
Tutorial is not yet updated but here's the example app in this repo: 

https://github.com/neo4j-contrib/django-neomodel/blob/master/tests/someapp/admin.py

**Comment by MajidHeydari** [comment]
Do I have to create a user table to log in? I can not use  python manage.py createsuperuser?

**Comment by whatSocks** [comment]
there's an example app here 
https://github.com/neo4j-examples/paradise-papers-django

**Comment by MajidHeydari** [comment]
To createuser, do I must build a model with a Django-neomodel or use the Django model by default ?

**Comment by whatSocks** [comment]
at this time, use the default django model

**Comment by MajidHeydari** [comment]
I made the app with neomodel but it is not created for admin
[https://github.com/MajidHeydari/neomodel-ninja](url)

**Comment by whatSocks** [comment]
ok we'll check it out @MajidHeydari

**Comment by whatSocks** [comment]
if you check the example, it says `neo_admin` for the neomodel parts

```
from django_neomodel import admin as neo_admin
from .models import Book

class BookAdmin(dj_admin.ModelAdmin):
    list_display = ("title", "created")
neo_admin.register(Book, BookAdmin)
```

in your admin, it says `dj_admin` 

```
class PersonAdmin(dj_admin.ModelAdmin):
    list_display = (
        "id",
        "name",
    )

dj_admin.site.register(Person, PersonAdmin)
```

**Comment by MajidHeydari** [comment]
So I have to use two databases like neo4j and sqlite at the same time to use the admin panel.These are the disadvantages of not being able to use the Django panel. One of the advantages of Django is the admin panel.

**Comment by whatSocks** [comment]
Yes - it's not ideal but until we build a DB Engine for Neo4j we will have to continue with two databases.

**Comment by roelandmoors** [comment]
Are there any plans to create a DB engine? Is that even possible since Django uses relational databases?
