### ISSUE TITLE
[Aura 4.0] python manage.py install_labels error with aura 4.0

### ISSUE THREAD

**Issue by danielwatabe** [neo4j-contrib/django-neomodel#62]
I see that some changes were made to work with neo4j+s format in the following PR:
https://github.com/neo4j-contrib/django-neomodel/commit/4398851be590ad9976f04aa0451cae08afac2878

**Attempt 1: using neo4j format**
If I don't change [neomodel/neomodel/config.py](https://github.com/neo4j-contrib/neomodel/blob/master/neomodel/config.py) encrypted to be True then I get the following error when running `python manage.py install_labels` using a neo4j URL, without the +s

```
\venv\lib\site-packages\neo4j\io\__init__.py", line 1042, in update_routing_table
    raise ServiceUnavailable("Unable to retrieve routing information")
neo4j.exceptions.ServiceUnavailable: Unable to retrieve routing information
```

**Attempt 2: using neo4j+s format**
If I do use the neo4j+s URL format then I get this other error:
```
\venv\lib\site-packages\neo4j\__init__.py", line 172, in driver
    URI_SCHEME_NEO4J_SECURE,
neo4j.exceptions.ConfigurationError: The config settings 'encrypted' and 'trust' can only be used with the URI schemes ['bolt', 'neo4j']. Use the other URI schemes ['bolt+ssc', 'bolt+
s', 'neo4j+ssc', 'neo4j+s'] for setting encryption settings.
```

Not sure if there is another way around this without changing the config file mentioned above in attempt 1.

**Comment by whatSocks** [comment]
Thanks, will check on this and https://github.com/neo4j-contrib/neomodel/issues/567 concurrently
